.appveyor.yml
asyncdispatch2.nimble
asyncdispatch2/asyncloop.nim
asyncdispatch2/sendfile.nim
asyncdispatch2/transports/common.nim
asyncdispatch2/transports/datagram.nim
asyncdispatch2/transports/stream.nim
tests/testdatagram.nim
tests/teststream.nim

Add Windows emulation of AF_UNIX sockets via Named Pipes.
Add tests for AF_UNIX sockets.
TransportAddress object change.

Add AF_UNIX sockets support.

---

asyncdispatch2.nimble
tests/config.nims

- reduce duplication in the Nimble "test" task
- delete test binaries

add "--threads:on" to tests

---

chronos.nimble
chronos/asyncloop.nim
chronos/timer.nim
chronos/transports/stream.nim
tests/testdatagram.nim
tests/testfut.nim
tests/testsignal.nim
tests/testsoon.nim
tests/testtime.nim

Old fast timers are available through compiler switch.
Add tests for both timers.

Introduce monotonic timer functions.

---

chronos.nimble
chronos/asyncfutures2.nim
chronos/transports/common.nim
chronos/transports/datagram.nim
chronos/transports/stream.nim
tests/testaddress.nim
tests/testall.nim
tests/testbugs.nim
tests/testdatagram.nim
tests/testfut.nim
tests/testserver.nim
tests/testsignal.nim
tests/testsoon.nim
tests/teststream.nim
tests/testsync.nim
tests/testtime.nim

Add tests for it.
Add fromProc for all Future[T] in transports.
Add testall to improve tests speed.
Bump version to 2.2.4.

Refactoring tests and fix rarely appearing Windows bug with close(transport).

---

chronos/transports/datagram.nim
tests/testdatagram.nim

Add broadcast feature for DatagramTransport.

---

chronos/asyncloop.nim
chronos/transports/datagram.nim
chronos/transports/stream.nim
tests/testdatagram.nim
tests/teststream.nim

1. Add simple tracking of Datagram and Stream transports.
2. Fix leaks in transports.
2. Fix leaks in tests.
3. Add leaks tests to Datagram and Stream transport tests.

Initial tracking mechanism.

---

chronos/asyncfutures2.nim
chronos/srcloc.nim

All the Future[T] operations using SourceLocation now.
fromProc is now cstring.

Add SourceLocation.

---

chronos/streams/asyncstream.nim
chronos/streams/chunkstream.nim

Add offset field to WriteItem.

Change AsyncStream close procedure from events to cancellation.

---

chronos.nimble
chronos/asyncmacro2.nim
chronos/streams/asyncstream.nim
chronos/streams/tlsstream.nim
chronos/transports/common.nim

Remove usage of getCurrentException().

---

chronos.nimble
chronos/transports/common.nim
chronos/transports/datagram.nim
chronos/transports/stream.nim
tests/testdatagram.nim

Add test for datagram's AnyAddress.
Bump version to 2.3.6.

Fix Windows datagram's AnyAddress issue.

---

chronos/asyncmacro2.nim
tests/testbugs.nim

Fix Nim's issue  https://github.com/nim-lang/Nim/issues/13889.
Add test for it.

Fix Nim's issue #13889

---

chronos.nimble
chronos/asyncfutures2.nim
tests/testfut.nim

Fix `or` for already finished futures.
Add tests.

Undeprecate `or` operation.

---

chronos.nimble
chronos/asyncmacro2.nim
tests/testbugs.nim

Incorporating fix https://github.com/nim-lang/Nim/pull/14723 for issue https://github.com/nim-lang/Nim/issues/13899

Fix async defer problem

---

chronos.nim
chronos.nimble
chronos/asyncfutures2.nim
chronos/asyncloop.nim
chronos/debugutils.nim
tests/testall.nim
tests/testutils.nim

Implementation of https://github.com/status-im/nim-chronos/issues/31 and https://github.com/status-im/nim-beacon-chain/issues/1121

[WIP] Zero-cost unattended Future[T] tracking mechanism.

---

chronos/asyncfutures2.nim

The cancellation process has a very complicated control flow, split over different files and hidden by macros. These comments should help shed a light on this madness.

cancelAndWait(): add comments

---

chronos/asyncmacro2.nim
tests/testfut.nim

Fix newFuture[T] location source for generated async procedures.

---

chronos/transports/common.nim
chronos/transports/stream.nim
tests/teststream.nim

Add tests for read() and write() deadlocks.

Fix deadlock for pending write() calls on transport close.

---

chronos/apps/http/httpserver.nim
tests/testhttpserver.nim

Add tests for drop().
Fix transport leak because of drop().

Add drop() implementation (was missed) to httpserver and fix transport leak.

---

chronos/apps/http/httpcommon.nim
chronos/apps/http/httpserver.nim

Add more respond() aliases.
Add responded() to check if response is already sent.

Fix contentType handling code.

---

chronos/apps.nim
chronos/apps/http/httpserver.nim
chronos/apps/http/shttpserver.nim
tests/testall.nim
tests/testhttpserver.nim
tests/testshttpserver.nim

This PR splits HTTP and HTTPS server implementations, so it become possible to use HTTP server without SSL library dependency.

Split HTTPS and HTTP servers.

---

chronos/asyncloop.nim

I was updating vendor modules in nim-waku and noticed withTimeout usage would still give issues.

Add raises annotation to withTimeout callbacks

---

chronos.nimble
chronos/asyncfutures2.nim
chronos/asyncloop.nim
chronos/asyncmacro2.nim
chronos/transports/stream.nim

Seems like a variation of https://github.com/nim-lang/Nim/issues/17369

add explicit gcsafe annotations (fixes #174)

---

chronos/apps/http/httpcommon.nim
chronos/apps/http/httpserver.nim
chronos/apps/http/multipart.nim
chronos/streams/asyncstream.nim
chronos/streams/boundstream.nim
chronos/transports/stream.nim
tests/testasyncstream.nim

Documentation for BoundedStream.
Fix HttpServer bounding.

Refactor, fixes and optimization of BoundedStream.

---

.appveyor.yml
.github/workflows/ci.yml
chronos.nimble
chronos/asyncfutures2.nim

This PR implements async stack traces when using nimStackTraceOverride.
https://gist.github.com/stefantalpalaru/71c4c176da5ac46ffa32564b431aa488
Note that "-d:disableLibbacktrace" was needed, thus disabling the stack trace override.
```text
[amd] 15 Mon Apr 26 21:51:04 |/mnt/sde1/storage/nimbus-eth2|
stefan$ ./env.sh nim c -r -f --hints:off -d:release -d:chronosStackTrace -d:disableLibbacktrace tmp/test16.nim
test exception
Async traceback:
/mnt/sde1/storage/nimbus-eth2/tmp/test16.nim(17)                                test16
/mnt/sde1/storage/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(1086)    waitFor
/mnt/sde1/storage/nimbus-eth2/vendor/nim-chronos/chronos/asyncloop.nim(279)     poll
/mnt/sde1/storage/nimbus-eth2/tmp/test16.nim(8)                                 p1 …
```

support nimStackTraceOverride

---

.github/workflows/ci.yml
chronos/streams/boundstream.nim
tests/testasyncstream.nim

Restore functionality of zero-sized bounded reader/writer streams.

---

README.md

apparently it has changed name

fix web framework name Looper -> Scorper

---

tests/testfut.nim

simplify future tests

---

chronos.nimble
chronos/apps/http/httpclient.nim
chronos/apps/http/httpcommon.nim
tests/testhttpclient.nim

Add tests for basic authorization.

Basic authorization implementation for HTTP client.

---

chronos.nimble
chronos/apps/http/httpclient.nim
chronos/apps/http/httpcommon.nim
chronos/apps/http/httpserver.nim
tests/testhttpserver.nim

Add simple test suite.
Bump version to 3.0.6.

Add `Accept` header handling to httpserver.nim.

---

chronos/apps/http/httpbodyrw.nim
chronos/apps/http/httpclient.nim
chronos/apps/http/httpcommon.nim
chronos/apps/http/httpserver.nim
chronos/streams/asyncstream.nim
chronos/streams/boundstream.nim
chronos/streams/chunkstream.nim
chronos/streams/tlsstream.nim

Fix async streams issue with replacing state.
Add `closing` states to HTTP's server connection, request and bodyrw.
Fix Http server cancellation leaks.

No more Defect on stream close.

---

chronos/transports/stream.nim
tests/teststream.nim

Fix issue #219

---

chronos/apps/http/httpserver.nim
chronos/handles.nim
chronos/transports/common.nim
chronos/transports/datagram.nim
chronos/transports/stream.nim

Handle accept() errors properly.

---

chronos/apps/http/httpclient.nim

* Fix `Connection: keep-alive` handling in HTTP client.
* Add unique connection identifier.

Fix connections management in http client.

---

chronos/asyncloop.nim
chronos/handles.nim
chronos/selectors2.nim
chronos/sendfile.nim
chronos/transports/common.nim
chronos/transports/datagram.nim
chronos/transports/stream.nim

This doesn't fix every error, but at least nimdoc doesn't segfault anymore

Fixes for nimdoc

---

chronos/apps/http/httpserver.nim
tests/testhttpserver.nim

Fix of the following bug:
In case of multiple accept headers with same preference
`preferredContentType` used to select the first match within content types
provided by the application. For example, if user specifies accept headers
`application/octet-stream, application/json` and application provides
`application/json, application/octet-stream`, `application/octet-stream`
will be returned, and that is a bug.
Now the procedure returns the most suitable match according
to the application preferences.

Refactor `preferredContentType` proc & add tests

---

chronos/asyncmacro2.nim
tests/testmacro.nim

And more tests. Follow up of #261

Handle multiple childs for opensymchoice

---

chronos/asyncsync.nim
tests/testsync.nim

AsyncEventBus: fix multiple listeners

---

chronos/timer.nim
tests/testtime.nim

Also adds `Moment.epochSeconds` and `Moment.epochNanoSeconds`

Add `high` and `low` operators for `Duration` and `Moment`

---

tests/testmacro.nim

Add test for nested finally transform issue

---

chronos/apps/http/httpserver.nim

Make contentLength field publicly available.

Fix HTTP content-length issues.

---

chronos.nimble
chronos/ratelimit.nim
tests/testall.nim
tests/testratelimit.nim

A regular token bucket
I added a manual replenish as @arnetheduck suggested

Token bucket

---

chronos/asyncmacro2.nim

Fix async macro "CannotRaise" warnings in nim >1.2

---

chronos/transports/stream.nim

@Menduist @arnetheduck please merge this!

fix int set

---

chronos/streams/tlsstream.nim

This PR fixes issue described in https://github.com/status-im/nim-chronos/pull/356

Properly fix SIGBUS crash issue 

---

tests/testmacro.nim

https://github.com/status-im/nim-chronos/issues/56

add test for raise-only patterns

---

chronos/asyncmacro2.nim

* prefer `let`
* prefer expressions
* renames

asyncmacro: code cleanups

---

chronos.nimble

last version to support Nim 1.2, 1.4 - may receive critical backports but otherwise this is EOL for said Nim versions

version 3.2.0

---

chronos/ratelimit.nim

future may be completed by worker before cancellation is set

ratelimit: set cancellation earlier

---

chronos/apps/http/httpbodyrw.nim
chronos/apps/http/httpclient.nim
chronos/apps/http/httpcommon.nim
chronos/apps/http/httpdebug.nim
chronos/apps/http/httpserver.nim
chronos/apps/http/shttpserver.nim
chronos/asyncloop.nim
chronos/asyncproc.nim
chronos/streams/asyncstream.nim
chronos/transports/datagram.nim
chronos/transports/stream.nim
chronos/unittest2/asynctests.nim
tests/testasyncstream.nim
tests/testdatagram.nim
tests/testhttpclient.nim
tests/testhttpserver.nim
tests/testproc.nim
tests/testshttpserver.nim
tests/teststream.nim

* Trackers simplification and helpers.
* Adding HTTP server trackers
* Refactor HTTP main processing loop.

Trackers refactoring.

---

chronos/apps/http/httpclient.nim
chronos/streams/tlsstream.nim

* Fix `NoVerifyServerName` do not actually disables SNI extension.
* Fix HTTP client SSL/TLS error information is now part of connection error description.

Some HTTPs related fixes.

---

tests/teststream.nim

Use random ports in bind to local address test

Use random ports

---

README.md

Better wording, runnable examples, and integrate https://github.com/status-im/nim-chronos/pull/445 changes

Update README regarding cancellation

---

chronos.nimble
nim.cfg

`chronosPreviewV4` is obsolete

simplify tests

---

chronos/internal/asyncfutures.nim
tests/testfut.nim

for convenience and compatibility

varargs overloads

---

chronos/apps/http/httpcommon.nim
chronos/apps/http/httpserver.nim
tests/testhttpclient.nim
tests/testhttpserver.nim
tests/testshttpserver.nim

Fix processing callback missing asyncraises.
Fix tests.

Asyncraises for HTTP server, part 2

---

chronos/apps/http/httpserver.nim
docs/examples/middleware.nim
docs/src/SUMMARY.md
docs/src/examples.md
docs/src/http_server_middleware.md
tests/testhttpserver.nim

Middleware support enables integrating custom number of custom applications into single HTTP server, it also allows to implement more comprehensive and more flexible CORS support, HTTP request rate limiting and HTTP response caching.
Example of request filtering by URI presented in test.

HTTP server middleware implementation.

---

chronos/internal/raisesfutures.nim
tests/testfut.nim

See https://github.com/nim-lang/Nim/issues/23432

make `Raising` compatible with 2.0

---

chronos/internal/asyncfutures.nim
tests/testfut.nim

Fix rare cancellation race issue on timeout for wait/withTimeout.

---

.github/workflows/ci.yml
chronos.nimble
chronos/streams/tlsstream.nim

See https://github.com/status-im/nim-bearssl/pull/62

add ubuntu 24 and gcc 14

---

chronos/apps/http/httpserver.nim
chronos/apps/http/shttpserver.nim
tests/testhttpserver.nim
tests/testshttpserver.nim

Fix H(S)ttpServer.baseUri should provide correct value for ANY_ADDRESS addresses.

---

chronos/internal/asyncfutures.nim
tests/testfut.nim

Allow cancelAndWait() accept multiple Futures for cancellation.
