- chronos/transports/common.nim
- chronos/transports/stream.nim
- tests/teststream.nim
With this PR behavior of handling `ECONNRESET` and `EPIPE` errors will be changed. This errors will not raise `TransportOsError` exception, but it will return `0` as return value from `write` procedures.
> Ignore ECONNRESET and EPIPE errors on sending.

- chronos.nim
- chronos.nimble
- chronos/asyncfutures2.nim
- chronos/asyncloop.nim
- chronos/asyncmacro2.nim
- chronos/asyncsync.nim
- chronos/streams/asyncstream.nim
- chronos/streams/chunkstream.nim
- chronos/transports/datagram.nim
- chronos/transports/stream.nim
- tests/testall.nim
- tests/testfut.nim
- tests/testmacro.nim
- tests/teststream.nim
- tests/testsync.nim
This is initial Future[T] cancellation proposal and implementation.
* The most significant changes were made in `asyncfutures2.nim` and `asyncmacro2.nim`.
* `asyncloop.nim` has 2 examples on how cancellation can be handled for simple procedures (which are not transformed with `async` macro).
* `asyncfutures2.nim` also has most problematic places such as `all()` and `and()` which is marked with `# TODO` comments. I really think that this procedures needs some care or deprecation.
* Most of other places are just `if not future.finished(): future.finish/fail()` because when cancellation happens, you must not `complete()` or `fail()` Future[T].
* Also there present fix for recently discovered `EINTR + connect` problem.
> [WIP] Initial cancellation proposal.

- chronos/transports/ipnet.nim
This typo was breaking nim's doc generator.
> Fix typo in doc string

- chronos/asyncfutures2.nim
- chronos/asyncmacro2.nim
This is rename of `FutureError` to `FutureDefect` because it is used only to raise "double Future[T] completion" error, so its exactly `Defect`.
`FutureError` will be still `CatchableError` and so `CancelledError` will be `CatchableError` too.
We also want to catch all exceptions in iterator's code, because otherwise exceptions will start leaking through `poll()` call and it will be hard to obtain proper stack trace for it.
> Revert back some exception changes.

- chronos/asyncloop.nim
This PR addresses two issues:
a) The current check for `isNil` doesn't seem to make much sense in this context. I was running into errors with `fut` completing twice, checking if `fut` finished seems to make much more sense. (546cc36d79d0ed104b95304922cf331fd0ca2f4b)
b) The entire `timers` list (heap), is being scanned on every `removeTimer` invocation, this incurs in a huge performance overhead when the amount of active timers reaches some threshold. For example, introducing timeouts to nim-libp2p would trigger this in tests pretty often, bringing execution to a complete stall. This PR addresses this issue by avoiding removing timers one by one and instead delay timer removal until the end of the `poll` execution and then cleans them up in wholesale. This increases performance and makes …
> Optimize timers processing

- chronos.nimble
- chronos/asyncfutures2.nim
- chronos/asyncloop.nim
- chronos/transports/stream.nim
- tests/testbugs.nim
- tests/testfut.nim
Fix bug cancellation handlers not called in wait() and withTimeout().
Fix double completion bug because of callback race.
Fix deprecation warnings.
Rename some internal procedures.
Bump version to 2.3.5.
> Fixes for cancellation bugs.

- chronos/streams/asyncstream.nim
The close state was written sometimes too late.
Fixed some issue with https://github.com/status-im/nim-libp2p/pull/131
> Fix possible race condition in asyncstream close

- chronos/transports/common.nim
Avoiding to have unnecessary exceptions in `raises:[]`.
> Remove unreachable raise from initTAddress

- chronos.nimble
- chronos/asyncfutures2.nim
- chronos/asyncloop.nim
- chronos/asyncmacro2.nim
- chronos/debugutils.nim
- tests/testutils.nim
- Make Future tracking optional via `-d:chronosFutureTracking` compilation flag.
- Make Future stack traces optional via `-d:chronosStackTraces` compilation flag.
- Address review comment https://github.com/status-im/nim-chronos/pull/107#pullrequestreview-442368768
> Make Future tracking and stack traces optional

- chronos.nimble
- chronos/transports/ipnet.nim
- tests/testnet.nim
* fixes call to `bigEndian32` on a uint64 which breaks on big endian
platforms
* prefer endians2 for less and safer code
> fix endian conversion issues

- chronos.nimble
- chronos/asyncfutures2.nim
- chronos/asyncloop.nim
You can see these metrics in action inside a nim-beacon-chain repo, by running `make NIMFLAGS="-d:insecure" eth2_network_simulation` and, a minute later in another terminal, `cd tests/simulation/prometheus; prometheus`.
Now you can go to [this address in your browser](http://localhost:9090/graph?g0.range_input=5m&g0.stacked=1&g0.expr=rate(chronos_processed_callbacks_total%7Bnode%3D%220%22%7D%5B2s%5D)&g0.tab=0&g1.range_input=5m&g1.stacked=1&g1.expr=rate(chronos_loop_timers_total%7Bnode%3D%220%22%7D%5B2s%5D)&g1.tab=0&g2.range_input=5m&g2.stacked=1&g2.expr=chronos_loop_timers_queue%7Bnode%3D%220%22%7D&g2.tab=0&g3.range_input=5m&g3.stacked=0&g3.expr=rate(chronos_poll_events_total%7Bnode%3D%220%22%7D%5B2s%5D)&g3.tab=0&g4.range_input=5m&g4.expr=rate(chronos_future_callbacks_total%7Bnode%3D%220%2 …
> some metrics for monitoring futures

- chronos/asyncfutures2.nim
When we document this procedure, we need to make it clear that exceptions are being raised in `poll()` by that new callback.
The name doesn't help at all.
> asyncCheck(): don't raise exception on cancellation

- chronos.nimble
- chronos/asyncfutures2.nim
- tests/testfut.nim
Deprecated asyncDiscard() procedure.
Bump version to 2.5.2.
> Add asyncSpawn() procedure and tests.

- chronos/asyncmacro2.nim
- chronos/asyncsync.nim
- chronos/transports/ipnet.nim
- tests/testsync.nim
* more efficient codegen for nil check (much less code)
* release futures earlier in AsyncEvent
* release finished future earlier in AsyncQueue
* avoid searches for futures (deque variant unused / broken)
* avoid catching defects
> small fixes

- chronos/asyncsync.nim
- tests/testsync.nim
Refactor `AsyncLock` to not use `result`.
Add test for `locked` flag.
> Fix AsyncLock.locked flag to be consistent.

- chronos/asyncfutures2.nim
- chronos/asyncloop.nim
this fixes a memory leak where a deleted callback may keep references
alive until the future is finished.
In particular, when using helpers like `or` which try to remove
themselves from the callback list when a dependent future is completed,
create a reference chain between all futures in the expression - in the
pathological case where one of the futures is completes only rarely (for
example a timeout or a cancellation task), the buildup will be
significant.
> release callback memory early

- chronos/asyncfutures2.nim
...or the compiler randomly gets confused when
`-d:chronosFutureTracking` is enabled
> rename newFuture proc's

- chronos/asyncfutures2.nim
- tests/testfut.nim
Add `race()` call which accepts not `Future[T]` but `FutureBase` objects.
This will allow to use `or` logic for more then two Futures, for example:
```nim
proc someProc1(): Future[string] {.async.} =
...
proc someProc2(): Future[seq[byte]] {.async.} =
...
await race(someProc1(), someProc2(), sleepAsync(100.milliseconds))
```
> Race() call

- chronos/asyncfutures2.nim
- chronos/asyncloop.nim
it seems that due to a naming conflict from asyncdispatch, callSoon is
deduced to raise exceptions even if it doesn't in modules that import
both, even indirectly - this patch randomly works around the issue with
some more overloads
> work around overload resolution issues

- chronos/transports/datagram.nim
IPV6_MULTICAST_HOPS already declared in posix.nim while IP_MULTICAST_TTL
has a value that will stay constant on linux/x86_64 - better codegen and
nlvm compat like this.
> use constant for ip kind

- README.md
...between `await` calls. Can no longer replicate.
> README: remove claim about temp var reordering

- chronos.nimble
- chronos/apps/http/httptable.nim
- tests/testhttpserver.nim
Switch to stew.base10 procedures.
Adjust tests to follow new behavior.
Bump version to 2.6.1.
> Fix integer decoding overflow issue.

- chronos/apps/http/httpserver.nim
- chronos/apps/http/httptable.nim
Fix response headers generation to avoid unnecessary computations.
> Add `server` and `host` headers handling.

- chronos/asyncloop.nim
- chronos/asyncmacro2.nim
Changed all places where asyncmacro2 might raise an exception:
- calls to `macros.$` are replaced by calls to `strVal`
- `%` formatting is replaced by string concatenation
- call to `parseExpr` (which might raise `ValueError`) is replaced by `newNimNode`
These changes also ensure that chronos works with Nim 1.4.4.
> Ensures that asyncmacro2 does not raise exceptions

- chronos.nimble
- chronos/transports/common.nim
- tests/testaddress.nim
* Fix comparison of `TransportAddress` issue.
* Add `resolveTAddress` procedures for both IPv4 and IPv6 addresses.
* Fix tests.
* Remove usage of `result` keyword.
* Change integer encoding/decoding procedures to stew/base10.
> Refactor common.nim and add more resolve procedures.

- chronos/asyncfutures2.nim
- chronos/asyncloop.nim
- chronos/asyncmacro2.nim
- chronos/handles.nim
- chronos/sendfile.nim
- chronos/transports/common.nim
- chronos/transports/datagram.nim
- chronos/transports/stream.nim
- tests/testbugs.nim
- tests/testdatagram.nim
Fix sources to follow 80 characters per line.
Fix unused compilation warnings.
Refactor (remove result) handles.nim.
Fix tests to use asyncSpawn instead of asyncCheck.
> Fix unused warnings, result, asyncCheck and 80 cpl

- chronos/transports/ipnet.nim
Currently, converting a `TransportAddress` from IPv4 to IPv6 or vice-versa will set the port to 0.
> Update `toIPv4` and `toIPv6` to keep the port

- .github/workflows/ci.yml
- chronos.nimble
This is an alternative to https://github.com/status-im/nim-chronos/pull/230
> CI: separate libbacktrace test in its own task

- chronos.nimble
This is a continuation of #231.
> properly move testing libbacktrace to a separate task

- .github/workflows/multi_nim.yml
This is an alternative to https://github.com/status-im/nim-chronos/pull/221 which would have marked all PRs and commits as failing.
The downside of a daily CI job is that you can forget about it, but at least it's there when you need it.
> CI: test multiple Nim branches in a daily cron job

- chronos/ioselects/ioselectors_epoll.nim
Include `IOSelectorsException` in addition to `Defect` in `raises: []`.
> add raises pragma to registerEvent in ioselectors_epoll

- chronos.nimble
- chronos/sendfile.nim
- chronos/transports/stream.nim
- tests/teststream.nim
When `write` is called on a `StreamTransport`, the current sequence of
operations is:
* copy data to queue
* register for "write" event notification
* return unfinished future to `write` caller
* wait for "write" notification (in `poll`)
* perform one `send`
* wait for notification again if there's more data to write
* complete the future
In this PR, we introduce a fast path for writing:
* If the queue is empty, try to send as much data as possible
* If all data is sent, return completed future without `poll` round
* If there's more data to send than can be sent in one go, add the
rest to queue
* If the queue is not empty, enqueue as above
* When notified that write is possible, keep writing until OS buffer is
full before waiting for event again
With this flow, as long as there is space …
> posix: fast path for write

- chronos/asyncfutures2.nim
- chronos/asyncmacro2.nim
Alternative to https://github.com/status-im/nim-chronos/pull/245
Simply removes FutureVar
Could have deprecated it, but since they weren't compiling for I don't know how long, not sure it's worth it
We can merge this or 245, as we want
> Remove future var

- chronos/asyncfutures2.nim
- chronos/asyncmacro2.nim
This PR modifies the async flow to improve RAM usage of async transformation.
Results, about half of ram consumption in nimbus:
(obviously, the RSS being sentient and having is own mind, it isn't divided by two, but actual consumption is)
The main goal is to rely as little as possible on mark & sweep, and rely instead on reference counting.
Reference counting fails on cyclic references, and also in other cases: https://github.com/nim-lang/Nim/issues/19193
So first step, add a workaround in `await` to avoid 19193.
Second step, more tricky, avoid cyclic reference of the closure/iterator.
Before this PR:
```nim
proc testInner(): Future[seq[int]] {.stackTrace: off, gcsafe.} =
var chronosInternalRetFuture = newFuture[seq[int]]("testInner")
iterator testInner_436207618(): FutureBase {.closure, …
```
> Improve ram usage

- chronos/transports/common.nim
`nim doc --project --index:on chronos.nim` was failing with the following error:
/path/to/nim-chronos/chronos/transports/common.nim(519, 21) Error: '*' expected
...which in turned caused errors in all files that import this one.
Now the entire docs can be built successfully, with only a few warnings.
Fixes #186.
> Fix documentation build

- chronos/streams/tlsstream.nim
When using multiple certificates (which is most real ones), this part can fail randomly:
https://github.com/status-im/nim-chronos/blob/b47b2a96ce824fa331a76877df0b1764a0bcb6d9/chronos/streams/tlsstream.nim#L712-L719
since the `res.storage.add(item.data)` _can_ reallocate a new sequence, and thus the previous `addr res.storage[offset]` now points to invalid data.
This PR is a simple fix for that, by allocating enough space to be sure that no allocation is needed. It will allocate a tad more than necessary, but I don't think that's an issue
> Fix TLS certificate allocation

- chronos/asyncmacro2.nim
- tests/testmacro.nim
Fixes https://github.com/status-im/nimbus-eth1/issues/963
For some reason, the code was generating this kind of AST for the return type:
```
Call
OpenSymChoice
Sym "[]"
Sym "[]"
...
Sym "Future"
Call
OpenSymChoice
Sym "[]"
Sym "[]"
..
Ident "seq"
Ident "OpenObject"
```
And this "recursive" OpenSymChoice wasn't handled properly by the macro
> Cleanup return type open syms

- chronos/asyncmacro2.nim
Currently, nim doc doesn't work on async procedures, because the comment will be move in the iterator, and thus won't be in the top procedure, eg:
```nim
proc test*() {.async.} =
echo 5
```
Transformed into
```nim
proc test*(): Future[void] {.stackTrace: off, gcsafe.} =
iterator test_436207618(chronosInternalRetFuture: Future[void]): FutureBase {.
closure, gcsafe, raises: [Defect, CatchableError, Exception].} =
block:
echo 5
complete(chronosInternalRetFuture)
etc
```
This PR copies the first comment (which, AFAIK is the only used by nimdoc) to the outer procedure, which fixes this issue
Ideally we would also extract the runnableExamples
> Fix nimdoc comment for async procs

- chronos/apps/http/httpclient.nim
Tracking of these flags is important for preventing pre-mature HTTP connection closing or inducing connection leaks.
> Fix missing connection flag.

- chronos/asyncloop.nim
- chronos/transports/datagram.nim
- chronos/transports/stream.nim
- tests/testsignal.nim
The socket selector holds a `seq` of per-descriptor data. When a reader
is registered, a pointer to a seq item is stored - when the `seq` grows,
this pointer becomes dangling and causes crashes like
https://github.com/status-im/nimbus-eth2/issues/3521.
It turns out that there already exist two mechanisms for passing user
data around - this PR simply removes one of them, saving on memory usage
and removing the need to store pointers to the `seq` data that become
dangling on resize.
> fix crash after reading from fd > 1024

- chronos/apps/http/httpclient.nim
When calling the HTTP `send` / `open` functions, `acquireConnection` is
called to obtain a connection in state `Ready`. In the next code block,
the connection state is advanced to `RequestHeadersSending`. However,
returning from chronos `async` procs yields control, similar to `await`.
This means that a connection may be added to the pool in `Ready` state,
and then a different `acquireConnection` call may obtain a second ref.
Introducing a new `Acquired` state ensures consistency in this case.
No tests added due to this being scheduler dependent; ran manual tests
by adding a `doAssert item.state != HttpClientConnectionState.Acquired`
between `if not(isNil(conn)):` and `return conn`. Eventually, the assert
got hit after several hours of repeated tests, confirming the edge case
to be solved …
> Guarantee exclusive use of `HttpClientConnection`.

- chronos/apps/http/httpclient.nim
- chronos/apps/http/httpcommon.nim
I've traced the problem to a HTTP connection being closed while there
are outstanding requests that still go through the motions (the crash
occurs when a requests reaches its `finish` processing step, but it
was already put in a Closed state by the connection that owns it).
> Tentative fix for the HTTP client connection state assertion failures

- chronos/apps/http/httpserver.nim
- tests/testhttpserver.nim
This is more optimized version for preferredContentType() which deprecates helpers usage and sorting of Accept header values array.
> Optimized implementation for preferredContentType() 

- chronos/apps/http/httptable.nim
- chronos/asyncloop.nim
- chronos/asyncsync.nim
- chronos/debugutils.nim
- chronos/handles.nim
- chronos/ioselects/ioselectors_epoll.nim
- chronos/sendfile.nim
- chronos/srcloc.nim
- chronos/streams/asyncstream.nim
- chronos/timer.nim
- chronos/transports/common.nim
- chronos/transports/datagram.nim
- chronos/transports/ipnet.nim
- chronos/transports/osnet.nim
- chronos/transports/stream.nim
A continuation of https://github.com/status-im/nimbus-eth2/pull/3888
Rationale (from that link):
> Currently (the latest commit in unstable branch), the CI log for the 1.6 branch has **107.000 lines**.
Removing every hint about cannot raise 'Defect' (including the ones in the vendor directory) leaves **16.000 lines**. 85% off.
> make it more Nim 1.4+ compatible

- chronos/asyncloop.nim
- tests/testbugs.nim
* Add GetQueuedCompletionStatusEx() support for Windows, which allows to capture more then one event in single `poll()` call.
This PR will fix
#308 
#242
> Fix nested waitFor (IndexError defect crash) bug.

- chronos/apps/http/httpclient.nim
- tests/testhttpclient.nim
This is proper fix for issue and replaces https://github.com/status-im/nim-chronos/pull/321.
With this fix
1. `NewConnectionAlways` global session flag which will create new connection for every HTTP request and close this connection after request's response received.
2. Added `HttpClientRequestFlag.DedicatedConnection` flag which will force to create new HTTP connection for this specific request. Note: Connection is not going to be closed.
3. `HttpClientRequestFlag.CloseConnection` flag will force HTTP client to send send `Connection: close` HTTP header with specific HTTP request and it also closes connection after response will be received.
So now, instead of using `NewConnectionAlways` you can specify both `DedicatedConnection` and `CloseConnection` to get equal behavior.
> HTTP client: Allow request connection management.

- chronos/asyncloop.nim
- chronos/asyncmacro2.nim
- tests/testmacro.nim
Allow `type = proc(...) {.async.}` for pre-declaring async callback types - in this case, the macro applies the correct transformation to the return type and adds the appropriate exception / gcsafe annotations
> `async` `proc` types

- chronos/asyncmacro2.nim
- tests/testmacro.nim
Fix `RetVoidType = proc(n: int) {.async.}` from #346 
Extract cleaner baseType computation from #251
> Fix `async` `proc` types & small cleanups

- chronos/transports/stream.nim
That's probably not the proper way to do it, but currently, TCP_NODELAY can only be enabled on the server, not on the client
> Enable TCP client to enable TCP_NODELAY

- chronos/transports/common.nim
- chronos/transports/ipnet.nim
- tests/testnet.nim
1. Remove `result` usage.
2. Switch from `cast[T]` usage to `endians2` usage.
3. Add more IPv4 and IPv6 helpers for TransportAddress checks and tests for it.
4. Add `isGlobal()` procedure to check IPv4 and IPv6 addresses are globally reachable (e.g. public). Add proper tests.
5. `isUnspecified()` check now checks for `0.0.0.0` and become alias for `isZero()` and `isNone()` check now checks for `AdressFamily.None`.
This PR superseeds https://github.com/status-im/nim-chronos/pull/352
> IpNet refactoring

- chronos/apps/http/httpbodyrw.nim
Instead of repeatedly checking stream 1, properly check all of them.
> fix `hasOverflow` for multiple streams

- chronos/apps/http/httpclient.nim
- tests/testhttpclient.nim
Add timestamps and duration for both HTTP client requests/responses.
> Add idle connection timeouts for HTTP client's connections pool.

- chronos/asyncloop.nim
- chronos/ioselects/ioselectors_epoll.nim
- chronos/ioselects/ioselectors_kqueue.nim
- chronos/osdefs.nim
- chronos/oserrno.nim
- chronos/osutils.nim
- chronos/selectors2.nim
- chronos/transports/common.nim
- chronos/transports/datagram.nim
- chronos/transports/osnet.nim
- chronos/transports/stream.nim
- tests/teststream.nim
This PR introduces fixes for latest `devel` changes, one of the fixes requires to have Posix error codes as constants.
* Introduced new file oserrno.nim which declares error constants for FreeBSD, OpenBSD, NetBSD, DragonflyBSD, MacOS and Linux.
* Fixed cast[pointer] warnings and errors.
* Fix usage of error constants.
* Deprecate `winlean` usage.
* Fix MacOS osnet.net issue.
> Fix cast[pointer] issues on nim-devel.

- chronos/asyncfutures2.nim
- chronos/debugutils.nim
- tests/testfut.nim
- tests/testutils.nim
* FutureState.Finished -> FutureState.Completed (to avoid name clash with `proc finished` which means not-pending)
* deprecate `done` - to avoid additional confusion over completed vs finished
* remove ad leftovers in stack trace formatting
> Future cleanup

- .gitignore
- chronos/transports/datagram.nim
My use case was to have several process running on the same host listening for udp broadcast on a given port.  I needed to setup the same 0.0.0.0:xxxx in each process and it works only if SO_REUSEPORT is set
> allow reuse of port for UDP

- chronos/ratelimit.nim
- tests/testratelimit.nim
Let the caller specify the "now" (which outside of tests, can be useful to avoid querying the clock multiple times, if the caller already knows the `now`)
In sync test, modify the `now` parameter instead of sleeping to avoid flakyness
In async tests, this is unfortunately not possible since the `worker` will actually sleep to wait for the bucket to fill
> Less flaky rate limit tests

- chronos/osdefs.nim
on x86_64, `EpollEvent` is packed - the upstream version is correct here
> fix EpollEvent memory layout

- chronos/streams/asyncstream.nim
I get this error when compile using Nim 1.16.12 in nimbus-eth1
```text
F:\projects\nimbus-eth1\vendor\nim-chronos\chronos\streams\asyncstream.nim(930, 5) template/generic instantiation of `join` from here
F:\projects\nimbus-eth1\vendor\nim-chronos\chronos\streams\asyncstream.nim(880, 14) Error: type mismatch: got <Future[system.void], proc (udata: pointer){.closure, gcsafe, locks: <unknown>.}, pointer>
but expected one of:
proc removeCallback(future: FutureBase; cb: CallbackFunc)
first type mismatch at position: 2
required type for cb: CallbackFunc
but expression 'continuation' is of type: proc (udata: pointer){.closure, gcsafe, locks: <unknown>.}
The `.raises` requirements differ.
proc removeCallback(future: FutureBase; cb: CallbackFunc; udata: pointer)
first type mismatch at position: 2 …
```
> Fix type mismatch error in asyncstream join

- chronos/asyncfutures2.nim
- chronos/asyncmacro2.nim
- chronos/futures.nim
- tests/testfut.nim
sometimes avoid copies when reading from `Future`
extracted from https://github.com/status-im/nim-chronos/pull/412
> futures: lentify

- README.md
- chronos/internal/asyncfutures.nim
- chronos/internal/asyncmacro.nim
- chronos/internal/raisesfutures.nim
- tests/testmacro.nim
Similar to the introduction of `raises` into a codebase, `asyncraises` needs to be introduced gradually across all functionality before deriving benefit.
This is a first introduction along with utilities to manage raises lists and transform them at compile time.
Several scenarios ensue:
* for trivial cases, adding `asyncraises` is enough and the framework deduces the rest
* some functions "add" new asyncraises (similar to what `raise` does in "normal" code) - for example `wait` may raise all exceptions of the future passed to it and additionally a few of its own - this requires extending the raises list
* som functions "remove" raises (similar to what `try/except` does) such as `nocancel` with blocks cancellations and therefore reduce the raising set
Both of the above cases are currently …
> introduce `asyncraises` to core future utilities

- README.md
- chronos/asyncloop.nim
- chronos/internal/asyncengine.nim
- chronos/internal/asyncfutures.nim
- chronos/internal/asyncmacro.nim
- chronos/internal/raisesfutures.nim
- tests/testmacro.nim
Per discussion in
https://github.com/status-im/nim-chronos/pull/251#issuecomment-1559233139, `async: (parameters..)` is introduced as a way to customize the async transformation instead of relying on separate keywords (like asyncraises).
Two parameters are available as of now:
`raises`: controls the exception effect tracking
`raw`: disables body transformation
Parameters are added to `async` as a tuple allowing more params to be added easily in the future:
```nim
proc f() {.async: (name: value, ...).}
```
> `asyncraises` -> `async: (raises: ..., raw: ...)`

- chronos/futures.nim
- chronos/internal/asyncfutures.nim
- chronos/internal/asyncmacro.nim
- docs/src/async_procs.md
- docs/src/concepts.md
- docs/src/error_handling.md
- docs/src/porting.md
Dedicated exceptions for `read` failures reduce the risk of mixing up "user" exceptions with those of Future itself. The risk still exists, if the user allows a chronos exception to bubble up explicitly.
Because `await` structurally guarantees that the Future is not `pending` at the time of `read`, it does not raise this new exception.
* introduce `FuturePendingError` and `FutureCompletedError` when `read`:ing a future of uncertain state
* ~~introduce `pollFor` which finishes a `Future` without reading it, mirroring `awaitne`~~
* fix `waitFor` / `read` to return `lent` values
* simplify code generation for `void`-returning async procs
* document `Raising` type helper
> dedicated exceptions for `Future.read` failures

- chronos/config.nim
- chronos/internal/asyncfutures.nim
- chronos/internal/asyncmacro.nim
- chronos/streams/tlsstream.nim
- chronos/transports/common.nim
- chronos/transports/datagram.nim
- chronos/transports/stream.nim
- tests/testfut.nim
This avoids copies here and there throughout the pipeline - ie `copyString` and friends can often be avoided when moving things into and out of futures
Annoyingly, one has to sprinkle the codebase liberally with `sink` and `move` for the pipeline to work well - sink stuff _generally_ works better in orc/arc
Looking at nim 1.6/refc, sink + local variable + move generates the best code:
msg directly:
```nim
T1_ = (*colonenv_).msg1; (*colonenv_).msg1 = copyStringRC1(msg);
```
local copy without move:
```nim
T60_ = (*colonenv_).localCopy1; (*colonenv_).localCopy1 =
copyStringRC1(msg);
```
local copy with move:
```nim
asgnRef((void**) (&(*colonenv_).localCopy1), msg);
```
Annoyingly, sink is also broken for refc+literals as it tries to changes the refcount of the literal as part of the move …
> futures: sinkify

- tests/testmacro.nim
> add a test for `results.?` compatibility

- chronos/apps/http/httpbodyrw.nim
- chronos/apps/http/httpclient.nim
- chronos/asyncsync.nim
- chronos/futures.nim
- chronos/internal/asyncfutures.nim
- chronos/internal/raisesfutures.nim
- chronos/streams/asyncstream.nim
- chronos/transports/common.nim
- chronos/transports/datagram.nim
- chronos/transports/stream.nim
* simplify `closeWait` implementations
* remove redundant cancellation callbacks
* use `noCancel` to avoid forgetting the right future flags
* add a few missing raises trackers
> prevent http `closeWait` future from being cancelled

- chronos/config.nim
Feature flags allow consumers of chronos to target versions with and without certain features via compile-time selection. The first feature flag added is for raise tracking support.
> Feature flag for raises support

- chronos/internal/asyncfutures.nim
- chronos/transports/datagram.nim
Using the callback setter may lead to callbacks owned by others being reset, which is unexpected.
* don't crash on zero-length UDP writes
> deprecate `callback=`, UDP fixes (fixes #491)

- chronos/config.nim
- chronos/streams/asyncstream.nim
- chronos/transports/common.nim
* Make buffer sizes configurable at compile time.
> Increase AsyncStream and Transport default buffer size from 4096 to 16384.

- chronos/internal/raisesfutures.nim
```nim
import chronos
proc f(): Future[void] {.async: (raises: []).} =
discard
discard f() or f() or f()
```
```
/Users/etan/Documents/Repos/nimbus-eth2/vendor/nim-chronos/chronos/internal/raisesfutures.nim(145, 44) union
/Users/etan/Documents/Repos/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(185, 28) []
/Users/etan/Documents/Repos/nimbus-eth2/test.nim(6, 13) template/generic instantiation of `or` from here
/Users/etan/Documents/Repos/nimbus-eth2/vendor/nim-chronos/chronos/internal/asyncfutures.nim(1668, 39) template/generic instantiation of `union` from here
/Users/etan/Documents/Repos/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(185, 28) Error: illegal conversion from '-1' to '[0..9223372036854775807]'
```
Fix by checking for `void` …
> fix conversion error with `or` on futures with `{.async: (raises: []).}`

- chronos/internal/asyncfutures.nim
- tests/testbugs.nim
- tests/testmacro.nim
> Fix `or` deadlock issue.

- chronos/internal/asyncfutures.nim
- tests/testfut.nim
I was initially checking `OwnCancelSchedule` flag being set in this primitives and after test i was agreed that its needed, because otherwise its hard to keep order of execution:
`wait()` and `withTimeout()` should not be cancelled() first, before `future` passed as argument will not be completed. So even `retFuture` become cancelled it should wait until situation with `future` will not be resolved.
> Ensure that `OwnCancelSchedule` flag will not be removed from wait() and withTimeout().

- chronos/internal/asyncfutures.nim
- tests/testfut.nim
We can check at compile-time that at least one parameter is passed
* clean up closure environment explicitly in some callbacks to release memory earlier
> Avoid `ValueError` effect in varargs `race`/`one`

- chronos/transports/stream.nim
In `stream.readLoop`, a finished `Future` was left in `transp.reader` if there was an error in `resumeRead`. Set it to `nil` as well.
> Ensure `transp.reader` is reset to `nil` on error

- chronos/internal/raisesfutures.nim
`failed` cannot return true for futures that don't forward exceptions
> print warning when calling failed

- chronos/apps/http/httpserver.nim
- chronos/internal/asyncfutures.nim
- chronos/streams/asyncstream.nim
- chronos/transports/datagram.nim
- chronos/transports/stream.nim
- tests/testfut.nim
This operation allows to monitor specific future and do not cancel it when `join()` was cancelled.
> Add `join()` operation to wait for future completion.

- chronos/apps/http/httpclient.nim
- tests/testhttpclient.nim
> Add ability to change httpclient's internal buffer size.

- chronos/streams/asyncstream.nim
For some reason it was returning `AsyncStreamWriter` instead of `AsyncStreamReader` instance.
> Fix AsyncStreamReader constructor declaration mistypes.
